name: docs
on:
  push: { branches: [main] }
  pull_request:
permissions: { contents: read, pages: write, id-token: write }
jobs:
  docs:
    uses: Zebradil/docs-kit/.github/workflows/docs.yml@e2fbc05a3e2ea04be6096b2e7aac74897a971a03 # v0.5.0
